export const mockJobs = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechViet JSC',
    companyLogo: '',
    location: 'Hà Nội',
    salary: '25-40 triệu',
    type: 'Full-time',
    level: 'Senior',
    tags: ['React', 'TypeScript', 'Tailwind'],
    postedAt: '2 ngày trước',
    deadline: '30/04/2026',
    description: 'Chúng tôi đang tìm kiếm Senior Frontend Developer có kinh nghiệm với React và TypeScript để xây dựng các sản phẩm web hiện đại.',
    requirements: ['3+ năm kinh nghiệm React', 'Thành thạo TypeScript', 'Kinh nghiệm với REST API', 'Hiểu biết về UI/UX'],
    benefits: ['Lương cạnh tranh', 'Bảo hiểm sức khỏe', 'Laptop công ty', '13 tháng lương'],
  },
  {
    id: '2',
    title: 'Backend Developer (Java)',
    company: 'FPT Software',
    companyLogo: '',
    location: 'Hồ Chí Minh',
    salary: '20-35 triệu',
    type: 'Full-time',
    level: 'Middle',
    tags: ['Java', 'Spring Boot', 'MySQL'],
    postedAt: '1 ngày trước',
    deadline: '15/04/2026',
    description: 'Tham gia phát triển hệ thống backend cho các dự án outsourcing lớn.',
    requirements: ['2+ năm kinh nghiệm Java', 'Spring Boot', 'SQL databases'],
    benefits: ['Review lương 2 lần/năm', 'Đào tạo nội bộ', 'Du lịch hàng năm'],
  },
  {
    id: '3',
    title: 'UI/UX Designer',
    company: 'Tiki Corporation',
    companyLogo: '',
    location: 'Hồ Chí Minh',
    salary: '18-30 triệu',
    type: 'Full-time',
    level: 'Junior',
    tags: ['Figma', 'Adobe XD', 'User Research'],
    postedAt: '3 ngày trước',
    deadline: '20/04/2026',
    description: 'Thiết kế giao diện người dùng cho ứng dụng thương mại điện tử hàng đầu Việt Nam.',
    requirements: ['1+ năm kinh nghiệm UI/UX', 'Thành thạo Figma', 'Portfolio ấn tượng'],
    benefits: ['Môi trường startup', 'Giờ làm linh hoạt', 'Stock options'],
  },
  {
    id: '4',
    title: 'DevOps Engineer',
    company: 'VNG Corporation',
    companyLogo: '',
    location: 'Hồ Chí Minh',
    salary: '30-50 triệu',
    type: 'Full-time',
    level: 'Senior',
    tags: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    postedAt: '5 ngày trước',
    deadline: '25/04/2026',
    description: 'Quản lý và tối ưu hóa hạ tầng cloud cho hệ sinh thái sản phẩm của VNG.',
    requirements: ['3+ năm kinh nghiệm DevOps', 'AWS/GCP', 'Docker & K8s', 'Scripting'],
    benefits: ['Top salary', 'Bonus hiệu suất', 'Đào tạo quốc tế'],
  },
  {
    id: '5',
    title: 'Mobile Developer (React Native)',
    company: 'MoMo',
    companyLogo: '',
    location: 'Hồ Chí Minh',
    salary: '22-38 triệu',
    type: 'Full-time',
    level: 'Middle',
    tags: ['React Native', 'JavaScript', 'iOS', 'Android'],
    postedAt: '1 tuần trước',
    deadline: '28/04/2026',
    description: 'Phát triển tính năng mới cho ứng dụng ví điện tử hàng đầu Việt Nam.',
    requirements: ['2+ năm React Native', 'Hiểu biết về native modules', 'Performance optimization'],
    benefits: ['ESOP', 'Bảo hiểm premium', 'Gym & wellness'],
  },
  {
    id: '6',
    title: 'Data Analyst',
    company: 'Shopee Vietnam',
    companyLogo: '',
    location: 'Hà Nội',
    salary: '15-28 triệu',
    type: 'Full-time',
    level: 'Junior',
    tags: ['Python', 'SQL', 'Power BI', 'Excel'],
    postedAt: '4 ngày trước',
    deadline: '22/04/2026',
    description: 'Phân tích dữ liệu kinh doanh và tạo báo cáo insights cho team Marketing.',
    requirements: ['1+ năm kinh nghiệm data analysis', 'Python/R', 'SQL', 'Visualization tools'],
    benefits: ['Lương tháng 14', 'Đào tạo từ Singapore', 'Văn phòng hiện đại'],
  },
];

export const mockUsers = [
  { id: '1', name: 'Nguyễn Văn A', email: 'a@email.com', role: 'candidate', status: 'active' },
  { id: '2', name: 'Trần Thị B', email: 'b@email.com', role: 'employer', status: 'active' },
  { id: '3', name: 'Lê Văn C', email: 'c@email.com', role: 'candidate', status: 'inactive' },
  { id: '4', name: 'Phạm Thị D', email: 'd@email.com', role: 'admin', status: 'active' },
  { id: '5', name: 'Hoàng Văn E', email: 'e@email.com', role: 'candidate', status: 'active' },
];

export const mockStats = {
  totalJobs: 1250,
  totalCandidates: 8500,
  totalEmployers: 320,
  totalApplications: 15600,
};
